create table channel_generator (
    id bigint generated by default as identity,
    account_secret text,
    accounts_left_to_create integer,
    is_refunded boolean,
    voting_id bigint not null,
    primary key (id)
);

create table channel_account (
    id bigint generated by default as identity,
    account_secret text,
    is_consumed boolean,
    is_refunded boolean,
    voting_id bigint not null,
    primary key(id)
);

alter table if exists channel_generator
   add constraint cstr_channel_generator_voting_id
   foreign key (voting_id)
   references voting;

alter table if exists voting
    add funding_account_secret text;

 alter table if exists channel_account
    add constraint cstr_channel_account_voting_id
    foreign key (voting_id)
    references voting;