create table voter_transaction (
    id bigint generated by default as identity,
    signature text not null,
    transaction text not null
);

alter table if exists voter_transaction
    add constraint cstr_voter_transaction_signature_unique unique (signature);