create table channel_generator (
    id bigint generated by default as identity,
    account_secret text,
    accounts_left_to_create integer,
    is_refunded boolean,
    voting_id bigint not null,
    primary key (id)
);

alter table if exists channel_generator
   add constraint cstr_channel_generator_voting_id
   foreign key (voting_id)
   references voting;