create table envelope_signature (
    id bigint generated by default as identity,
    signature text not null,
    voting_id bigint not null,
    user_id bigint not null,
    primary key (id)
);

alter table if exists envelope_signature
    add constraint cstr_envelope_signature_voting_id
    foreign key (voting_id)
    references voting;

alter table if exists envelope_signature
    add constraint cstr_envelope_signature_user_id
    foreign key (user_id)
    references users;